version: '3.0'

services:
    php:
        image: nanoninja/php-fpm:latest
        volumes:
            - ./html:/var/www/html
        links:
            - db
            
    db:
        image: mysql:5.7
        volumes:
         - /var/lib/mysql
        environment:
         - MYSQL_ROOT_PASSWORD=123456
         - MYSQL_DATABASE=database
        ports:
         - "3306:3306"
